[package]
name = "faradenza"
version = "0.1.0"
authors = [""]
edition = "2018"
publish = false

[dependencies]
crc = "1.8.1"
csv = "1.0.7"
rayon = "1.0.3"
regex = "1.1.7"
rocket = "0.4.1"
rocket_contrib = "0.4.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0.92"